### PR TITLE
Crc bootloader

### PR DESCRIPTION
**Pull request by rusefillc**

### CODE REVIEW

**Comment by mck1117** [comment]
Why extern c?

**Comment by rusefillc** [comment]
because that's the only way I can get it green and code reuse .h between BL and firmware

**Comment by mck1117** [comment]
1. crc32inc was missing, so tunerstudio may compile but it wouldn't link.
2. it needed separate `extern "C"` because you hadn't included `crc.h` in `crc.cpp`, but it turns out it was also necessary in the header too.

**Comment by rusefillc** [comment]
Approved

**Pull request merged**
