### PR TITLE
f1_rev and threads

### PR DESCRIPTION
**Pull request by dron0gus**
Set high speed mode for PWM gpio to source more current for VND14

Enable CH_CFG_USE_REGISTRY for all F1 boards and set name for all thread. So GDB can show thread names.

### CODE REVIEW

**Comment by mck1117** [comment]
> Enable CH_CFG_USE_REGISTRY for all F1 boards and set name for all thread. So GDB can show thread names.

oop, I'd turned that off to save memory, forgot that GDB uses it 😮

**Comment by mck1117** [comment]
> Set high speed mode for PWM gpio to source more current for VND14

Does this actually make a difference in our case? There's a 1k resistor in series with the gate. Slower edge rates will reduce EMI.

image

**Comment by dron0gus** [comment]
> Does this actually make a difference in our case? There's a 1k resistor in series with the gate. Slower edge rates will reduce EMI.

I have VND7NV04 on my board. And GD32.
With 2MHz output mode I see 2.7V high level on MOSFET input.
With 50MHz output mode I see 3.15V high level.
With 2MHz output mode Drain voltage is 1.25V (!!!) when MOSFET is on. 
With 50MHz output mode it drops to less than 0.5V
BTW, VND7NV04 define most of characteristics for Vin >= 3.5V...

**Comment by dron0gus** [comment]
Screenshot from 2022-12-13 01-07-07

**Comment by mck1117** [comment]
That's sort of crazy it has that much impact on the DC behavior.

**Comment by mck1117** [comment]
Do we think this has any relation to https://github.com/rusefi/rusefi-hardware/issues/161?

**Pull request merged**
