### PR TITLE
board: common make script

### PR DESCRIPTION
**Pull request by rusefillc**
(cherry picked from commit cb087c60e9f0d1d7ee8130c023ba99cdc428765c)

### CODE REVIEW

**Comment by mck1117** [comment]
Is this indeed common, or is this for a particular board? There are no plans to switch the hellen f0 module to use openblt, or use anything other than its current crc-appended firmware image format.

**Comment by rusefillc** [comment]
looks like it would be shared between F103 single and F103 dual?

**Comment by rusefillc** [comment]
what's your suggestion if we plan to use for both F103 but probably not F042?

**Comment by dron0gus** [comment]
@mck1117 please this one next.

**Pull request merged**
