### PR TITLE
sampling: use array instead of r_1, r_2, r_3

### PR DESCRIPTION
**Pull request by rusefillc**
(cherry picked from commit 4e7d2b4ed8c3254ba2be812b489e07e2a16d00d9)

### CODE REVIEW

**Comment by mck1117** [comment]
Yeah, this generates much worse code due to all of the array index modification.

Remember, the existing implementation only costs two additional instructions to do the "shift history over by one" since we already have those values loaded in registers.

**Comment by mck1117** [comment]
Not to mention that it adds a branch (`if (idx == 3)`) which costs something too.

**Comment by mck1117** [comment]
Current implementation: https://godbolt.org/z/c7Y6aeMor
Proposed implementation: https://godbolt.org/z/K3j3hYb54

**Comment by dron0gus** [comment]
@mck1117 one reason - easier to read.
Second reason - attempt to make 4-phace AC calculation. Failed. https://github.com/rusefi/wideband/pull/6/commits/4caf09019755f4cba8f47b6bf5fc066e1183c61c

**Comment by mck1117** [comment]
I'm going to disagree that this is easier to read.
image
Closing for now unless we can find a benefit to doing it this way.

**Pull request closed without merging**
