### PR TITLE
Extract io

### PR DESCRIPTION
**Pull request by rusefillc**
explicit header for shared IO pins shared by firmware and bootloader

i suspect that nerst is burred somewhere else but this PR is a start right?

### CODE REVIEW

**Comment by mck1117** [comment]
The new header should go in the f0_module folder, no?

**Comment by rusefillc** [comment]
stuff was hard coded in main.cpp and sampling.cpp outside of f0_module 

making new header per-board is a legit separate implement and I am happy to oblige if you request so. but with stuff hard-coded generally outside of modules this PR is an atomic step forward in my opinion

**Comment by mck1117** [comment]
we already add the module folder to the include path, btw, so just moving the existing file will work

**Comment by rusefillc** [comment]
moved

**Pull request merged**
