### PR TITLE
only f0 change to follow the convention

### PR DESCRIPTION
**Pull request by rusefillc**

### CODE REVIEW

**Comment by mck1117** [comment]
see 43def3f98257850f7820503f0984cda0e3c078d0

**Comment by rusefillc** [comment]
@mck1117 I see differences, do you not?

**Comment by mck1117** [comment]
The deliver dir should contain the files useful for the setup and update of that particular board. F0 module now uploads:

image

The bin is for flashing a new board, the header is read by rusEFI to flash boards in-situ over CAN.

What is there to change?

**Comment by rusefillc** [comment]
image

**Comment by mck1117** [comment]
There's no way to dfu these boards, as they don't have USB. Besides, the full image doesn't ever get assembled (crc footer, etc) as anything other than a bin, see build script line 27-39.

**Pull request closed without merging**
