### PR TITLE
PB6 with hardware mod is the simplest way forward

### PR DESCRIPTION
**Pull request by rusefillc**
failed blue pill test - no life on PB6 according to logic analyzer, I was expecting at least preheat even while no real hardware

### CODE REVIEW

**Comment by rusefillc** [comment]
@NMSTEC wanna have a look get life out of PB6?

**Comment by mck1117** [comment]
wait, what issue are we solving here?

**Comment by mck1117** [comment]
>  I was expecting at least preheat even while no real hardware

this is not necessarily true

**Comment by rusefillc** [comment]
I am trying to get current hardware to WBO

current heater control pin PC13 is not a timer pin
between integrating callback and software toggle I chose to recommend hardware mod of existing hardware with a nasty jumper wire to PB6

I wonder what do I need to see PWM on PB6 on the bench? would that require real board and anything else or would just blue pill work?

**Comment by rusefillc** [comment]
@mck1117 poke

**Comment by mck1117** [comment]
does this match changes in the `dron` branch, or does this diverge?

**Comment by rusefillc** [comment]
@dron0gus has used this commit in ``dron`` branch

**Pull request merged**
