### PR TITLE
update link to user doc

### PR DESCRIPTION
**Pull request by mi-hol**
avoid redirection

### CODE REVIEW

**Comment by mck1117** [comment]
why do we want to avoid redirect? isn't the point of the short link that we don't have to go change all our links if we move the wiki?

**Comment by mi-hol** [comment]
valid input, now it's the only short link I have come across until now.
At this stage it prevents searching for broken links.
Would you remember who created it and if the "bigger picture" for short links is documented?

**Comment by mck1117** [comment]
https://github.com/rusefi/web_backend/tree/master/www/s

**Comment by mi-hol** [comment]
Thanks Matt, added this new information to HOWTO-contribute-to-documentation.md via https://github.com/rusefi/rusefi_documentation/pull/425

**Pull request closed without merging**
